# Generated by Django 2.2 on 2019-04-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190411_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographs',
            name='bio',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='cost',
            field=models.PositiveSmallIntegerField(verbose_name='Стоимость услуг'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='firstname',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='instagram',
            field=models.URLField(verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Штатный фотограф'),
        ),
        migrations.AlterField(
            model_name='photographs',
            name='lastname',
            field=models.CharField(max_length=32, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='MultipleImagePhotographs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photograph', verbose_name='Фотография')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Photographs', verbose_name='Фотограф')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
    ]
