# Generated by Django 2.2 on 2019-04-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190411_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimagephotographs',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Photographs', verbose_name='Фотограф'),
        ),
    ]
