# Generated by Django 2.2 on 2019-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190414_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='areas', verbose_name='Главное изображение')),
                ('rent_cost', models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость аренды')),
                ('tax_weekends', models.PositiveSmallIntegerField(default=0, verbose_name='+ Выходные')),
                ('tax_latetime', models.PositiveSmallIntegerField(default=0, verbose_name='+ Позднее время')),
            ],
            options={
                'verbose_name': 'Зал и локация',
                'verbose_name_plural': 'Залы и локации',
            },
        ),
    ]
