# Generated by Django 2.2 on 2019-04-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photograph', verbose_name='Фотография')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Area', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
