# Generated by Django 2.2 on 2019-04-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_multiplestuffareas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleStuffAreas',
        ),
    ]
