# Generated by Django 2.2 on 2019-04-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_multiplestuffareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Бронирования / Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='BookingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Тип бронирования',
                'verbose_name_plural': 'Бронирования / Типы бронирования',
            },
        ),
    ]
