# Generated by Django 2.2 on 2019-04-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_area_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('bio', models.TextField(verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Стоимость услуг')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Штатный визажист')),
            ],
            options={
                'verbose_name': 'Визажист',
                'verbose_name_plural': 'Визажисты',
            },
        ),
        migrations.CreateModel(
            name='MultipleImageMakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photograph', verbose_name='Фотография')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.Makeup', verbose_name='Визажист')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Примеры работ',
            },
        ),
    ]
