# Generated by Django 2.2 on 2019-05-04 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190504_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=8192, verbose_name='Текст статьи')),
                ('image', models.FileField(upload_to='news', verbose_name='Обложка')),
                ('approved', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'saray_manager'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-approved', '-created_at'),
            },
        ),
    ]
